### ISSUE TITLE
Add support for validation

### ISSUE THREAD

**Issue by dazed-n-focussed** [shuyu/angular-material-fileinput#11]
It would be nice if we could add the ability to do some validations such as file size, required etc.

**Comment by shuyu** [comment]
ok i will make as soon as i can !!

**Comment by shuyu** [comment]
Hi ~ i already add validation feature on last release. If has any problem please me know. Thanks!

**Comment by dazed-n-focussed** [comment]
Hi there !

Thanks for the making the change and that too so fast. I was caught up with some other features. I will try out the validation feature asap. I am assuming you have something in your demos that show how its done.

**Comment by dazed-n-focussed** [comment]
I just went through your commit and your changes to the readme file. Thats awesome. I will try it out .There is 1 more type of validation that would be nice to have. Validation for the mimetype.
