### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by naumanahmed19** [shuyu/angular-material-fileinput#13]
Hi,
I want to use this component in my project but i am not sure how to use it. 

How can i get value in scope? and  is there any way that i can use  ng-model 

Thanks

**Comment by shuyu** [comment]
Hi ~ i think below code can give some help.

```html
<div ng-controller="DemoController">
    <lf-ng-md-file-input lf-files="files01"></lf-ng-md-file-input>
</div>
```
The lf-files attribute is working same as ng-model, so you should fetch data from $scope.files01

```js
var app = angular.module('demo', ['ngMaterial','lfNgMdFileInput']);
app.controller('DemoController',function($scope){
    $scope.$watch('files01.length',function(newVal,oldVal){
        console.log($scope.files01);
    });
});
```
After you selected file it should console a array on Developer Tool, then you can get what you want from objects . 
e.g. If you only want get files to upload via ajax you should enum files01 and get file from lfFile property.

**Comment by makerj** [comment]
I'm using this components for AJAX Request which uploads profile image.
As shuyu mentioned above, you can get javascript `File` object like this:

1.Write html template
```
<md-input-container class="md-block">
    <label>NICKNAME</label>
    <input ng-model="nickname">
</md-input-container>

<md-input-container class="md-block">
    <lf-ng-md-file-input lf-placeholder="PROFILE IMAGE" lf-files="profile_image"></lf-ng-md-file-input>
</md-input-container>

<md-button class="md-raised md-primary" ng-click="confirm()">Confirm</md-button>
```

2.Implement controller (including scope variable declaration)
```
var app = angular.module('demo', ['ngMaterial','lfNgMdFileInput']);
app.controller('DemoController',function($scope){
    $scope.nickname = null;
    $scope.someimg = [];
    $scope.confirm = function () {
        var data = new FormData();
        data.append('nickname', $scope.nickname);
        data.append('profile_image', $scope.profile_image[0].lfFile);
        
        /*rest of AJAX Request codes... */
    }
}
```

**Comment by naumanahmed19** [comment]
@shuyu  thanks for snippet. yes I am able to get image data now.  but I am little confused that how can i use in my forms.

right now on submitting form i am getting json object (item_info) with all fields data. should i merge or bind `file01` and `item_info` or there is a better way to do this

**Comment by naumanahmed19** [comment]
okay that's how i did it
`
var logo =  $scope.files01[0].lfFileName;
$scope.item_info.logo =logo;
`

**Comment by shuyu** [comment]
Thanks for your recommend ~ I still look for a good solution to implement that ...

**Comment by tkoykoy** [comment]
hi.. how can i get the file data?. i want to save that in another folder

**Comment by locddspkt** [comment]
How can I post this to php manually. I try to post the form but $_FILES is empty. I post all the form and do not use AJAX.

The question is how to use this with the classical type
Currently i use
<input name='image' type='file'/>

How do I replace this classical with the new style using angular-material-fileinput?

**Comment by ayaolwan** [comment]
How can I post this to php manually. I try to post the form but $_FILES is empty. I post all the form and do not use AJAX.

The question is how to use this with the classical type
Currently i use
<input name='image' type='file'/>

How do I replace this classical with the new style using angular-material-fileinput?

Do you solving this problem ?

 I need help in  same topic

**Comment by ayaolwan** [comment]
@locddspkt
