### ISSUE TITLE
Upload image 

### ISSUE THREAD

**Issue by alcinovanrooyen** [shuyu/angular-material-fileinput#14]
Hi how would i upload the file to a php API? that looks like this:
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    $destination = "myUrl";

    $postData = json_decode(file_get_contents('php://input'), true);
    
    $filename = $_FILES['image']['name'];

    move_uploaded_file($_FILES['image']['tmp_name'], $destination);

}

**Comment by shuyu** [comment]
Hi ~ i'm not very familiar with php, but the file post request from browser should send by form-data not json. so it should not use something like json_decode.

**Comment by erajay** [comment]
Hii....For  php you can use $_FILES array for requesting  all file format array then use loop upload files

remove values from array using loop

$name= $_FILES['files']['name'];
$path = public_path('uploads/' . $name);
move_uploaded_file($_FILES['files']['tmp_name'] , $path);

**Comment by alcinovanrooyen** [comment]
Hi... thanks for responding.

My problem seemed to be that i never had the below code in my php file and therefore couldn't access the file Flow was posting to the API:

//some flow stuff
$tempDir = __DIR__ . DIRECTORY_SEPARATOR . 'temp';
if (!file_exists($tempDir)) {
    mkdir($tempDir);
}

if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $chunkDir  = $tempDir . DIRECTORY_SEPARATOR . $_GET['flowIdentifier'];
    $chunkFile = $chunkDir.'/chunk.part'.$_GET['flowChunkNumber'];
    if (file_exists($chunkFile)) {
        header("HTTP/1.0 200 Ok");
    } else {
        header("HTTP/1.1 204 No Content");
    }
}
