### ISSUE TITLE
Not working while angular debug is off

### ISSUE THREAD

**Issue by EndarValuk** [shuyu/angular-material-fileinput#16]
Hello, my friend!
Found blocking "bug".
When angular application is working in "Production mode":
`angular.module('appModule').config(['$compileProvider',
  function($compileProvider) {
    $compileProvider.debugInfoEnabled(false);
}]);`
Then, your control is not working. When I try to select file it throws me an error:
`onFileChanged is undefined`.

**Comment by shuyu** [comment]
ok ~ i will check this problem !!

**Comment by shuyu** [comment]
Hi ~ this is fixed now. 
Thanks for your help!!

**Comment by EndarValuk** [comment]
TX! Working!
