### ISSUE TITLE
Multiple mimetype how use 

### ISSUE THREAD

**Issue by erajay** [shuyu/angular-material-fileinput#19]
Please explain hows we can use multiple files like pdf , image etc

**Comment by shuyu** [comment]
hi ~ the mimetyp is check by regex.
so you can write like 
```
//alow all image type and pdf file
<lf-ng-md-file-input lf-files="files" accept="image/* | application/pdf"></lf-ng-md-file-input>

//alow jpg and png
<lf-ng-md-file-input lf-files="files" accept="image/png | image/jpge"></lf-ng-md-file-input>

```
hope this help!!

**Comment by erajay** [comment]
i want this for validation purpose so please explain with ng-messages hows we can show validations ..

**Comment by shuyu** [comment]
Hi ~ Do you mean this ?  
```
<lf-ng-md-file-input name="files" lf-files="files" lf-mimetype="image/*|application/pdf" multiple>
   <div ng-messages="testForm.files00.$error" style="color:red;">
       <div ng-message="mimetype">Mimetype error.</div>
   </div>
</lf-ng-md-file-input>
```

**Comment by erajay** [comment]
For other formats like doc , xls  , sql ...

**Comment by shuyu** [comment]
hi ~
you can try to look for in this websit
[http://www.sitepoint.com/web-foundations/mime-types-complete-list/](http://www.sitepoint.com/web-foundations/mime-types-complete-list/)

**Comment by erajay** [comment]
hi 
i am trying to allow ms word file using "application/msword" according to link but its not working any suggestion .....

**Comment by shuyu** [comment]
Hi
Maybe you can check from this web [](http://mime.ritey.com/)
As i test the .docx file's mimetype is "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

**Comment by erajay** [comment]
Thanks its working fine .
