### ISSUE TITLE
Error when using drag feature, button works.

### ISSUE THREAD

**Issue by dustinengle** [shuyu/angular-material-fileinput#20]
Currently converting from bootstrap to material and this package is great.  Thank you.  

I get the following error message when I try to use the drag and drop feature.  Using the upload button works fine.  I think this might have something to do with jQuery being used.

> Uncaught TypeError: Cannot read property 'files' of undefined(anonymous function) 
@ lf-ng-md-file-input.js:389
jQuery.event.dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549

The line of code that is giving the issue is in the drop event handler:
```javascript
389: var files = e.target.files || e.dataTransfer.files;
```

It works fine if I re-assign the event with the original, if exists:
```javascript
389: if (angular.isObject(e.originalEvent)) e = e.originalEvent;
390: var files = e.target.files || e.dataTransfer.files;
````

Any help is greatly appreciated.

**Comment by shuyu** [comment]
Thanks so much !!!
I will fix it !
