### ISSUE TITLE
How to populate the preview when we have the image url?

### ISSUE THREAD

**Issue by vik228** [shuyu/angular-material-fileinput#22]
hey,
I have some image urls and i want to populate the files model in the same format as its when using browse. How can i do this? and also is there any event that gets generated on selecting files?

**Comment by asaptf** [comment]
I also interesting in that, I suppose it's very important: how to populate preview while opening page to show previously uploaded files, to have ability to change picture?
Thanks.

**Comment by davasqueza** [comment]
+1

**Comment by yb11206** [comment]
+1

**Comment by shuyu** [comment]
Hi guys, sorry to waiting so long. I will add an api for add preview url in next release.

**Comment by strongant** [comment]
That's greate!Probably when can release?

**Comment by antonForsberg** [comment]
+1

**Comment by inakrin** [comment]
+1

**Comment by softsara** [comment]
+1

**Comment by Greyg-POPEI** [comment]
Hi, it's possible now or we have to wait ? :)

**Comment by davasqueza** [comment]
![image](https://cloud.githubusercontent.com/assets/8594429/21529523/119ada52-cd08-11e6-8ffd-621196179171.png)


Thank you so so so much @shuyu , very useful 😃

**Comment by shuyu** [comment]
Hi ! Sorry for waiting so long,  I just add a api call addRemoteFile and hope is can work as yours thought.
