### ISSUE TITLE
spinner or progressbar for upload

### ISSUE THREAD

**Issue by chakuze** [shuyu/angular-material-fileinput#24]
hey,
is there an easy way to implement a spinner or a progressbar that indicates how much time is left to upload?

**Comment by shuyu** [comment]
hi sorry to reply so late . i think is depend on how you implement file upload , maybe you can refer from [http://stackoverflow.com/questions/23219033/show-a-progress-on-multiple-file-upload-jquery-ajax](http://stackoverflow.com/questions/23219033/show-a-progress-on-multiple-file-upload-jquery-ajax)
