### ISSUE TITLE
Not able to clear selected file after submitting of the form

### ISSUE THREAD

**Issue by praveenpds** [shuyu/angular-material-fileinput#27]
Im facing issue in clearing selected file after submitting of the form .

view :

<lf-ng-md-file-input 
lf-mimetype="audio/*"
 lf-files='testModel' lf-placeholder="test voice note *"
                                                                         lf-filesize="99KB" accept="audio/*"
                                                                         lf-browse-label=""
                                                                         lf-remove-label=""></lf-ng-md-file-input>
after post im executing this below peice of code for clearing the files selected previously

ctrl :
$scope.testModel = undefined.

**Comment by shuyu** [comment]
hi ~ you need use "lf-api" to intergrate with lf-files 

view:
<lf-ng-md-file-input lf-files="testModel" lf-api="lfApi"></lf-ng-md-file-input>

ctrl:
lfApi.removeAll()

hope this helps !!

**Comment by praveenpds** [comment]
cool. Working fine :)
