### ISSUE TITLE
Multiple lf-mimetype

### ISSUE THREAD

**Issue by musabgosset** [shuyu/angular-material-fileinput#39]
Hello, 

I can't put multiple lf mimetype without having validation errors : 

lf-mimetype="image/png,image/gif" won't work but accept="image/png,image/gif" will work.

Any idea ?

Thank you

**Comment by elephantsy** [comment]
Hi,

multiple mimetype is checked by regex so you should use **|** instead of **,**

**lf-mimetype="image/png|image/gif|application/pdf"**

and for accept you can also use it like this:

**accept=".png,.gif,.pdf"**


best,

E

**Comment by shuyu** [comment]
Thanks @elephantsy ! After version 1.5.0 use lf-mimetype="image/png,image/gif" will alos work !
