### ISSUE TITLE
Single File - Validation not working properly

### ISSUE THREAD

**Issue by shawnlan** [shuyu/angular-material-fileinput#53]
With single file upload, if I first choose a non-valid file, without removing it, select another valid file (overwrite previous one), the validator will not be called. Thus, the input remains invalid.

The issue doesn't exist the other way around. Weird.

**Comment by shawnlan** [comment]
Here is what I found:

scope.$watch('lfFiles.length') is not reliable enough. I put ctrl.$validate() inside of function readFile to fix this issue.

Another thing is that the setTimeout is not set up correctly with setTimeout(readFile(file), i*100);

It should be setTimeout(function(){readFile(file);}, i*100);

Otherwise readFile(file) is called right away.

**Comment by shuyu** [comment]
Hi ! Thanks so much for you feedback ! I just fixed these bugs on version 1.5.0 !
