### ISSUE TITLE
Not working in Firefox  +angular 1.6  angular material 1.1.1

### ISSUE THREAD

**Issue by pgrisafi** [shuyu/angular-material-fileinput#57]
In chrome no problem

In ff the dialog is never open, because

    var elFileinput = event.target.children[2];

elFileinput is always undefined
but using angular 1.5.9 it works!
(angular 1.6 keeps breaking my stuff!)

**Comment by elephantsy** [comment]
I had the same issues and based on the Live Demo the solution appears to be using angular 1.5.0

**Comment by shuyu** [comment]
Hi ! I just fixed it on version 1.5.0. If still not work please let me know. Thanks !!

**Comment by pgrisafi** [comment]
Sorry abut the delay, seems to be working just fine.
